In [12]:
import torch
from matplotlib import pyplot as plt
import numpy as np
import cv2
import os

In [13]:
model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5/runs/train/exp17/weights/last.pt', force_reload=True)

Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to C:\Users\user/.cache\torch\hub\master.zip
YOLOv5  2022-6-23 Python-3.9.5 torch-1.8.2+cpu CPU

Fusing layers... 
Model summary: 213 layers, 7018216 parameters, 0 gradients, 15.8 GFLOPs
Adding AutoShape... 


In [14]:
model.conf = 0.7
for path, subdirs, files in os.walk("yolov5/data/sub_dataset"):
    for name in files:
        img = path + "/" + name
        print(name)
        results = model(img)
        print(results.xyxyn[0][:, :].numpy())

1000.png
[[    0.62046     0.82752     0.90512     0.93644     0.92826           2]
 [    0.18783    0.040028     0.37043     0.31494     0.90715           2]
 [     0.1742     0.30551     0.46497     0.56522     0.89771           2]
 [    0.38835     0.58465     0.46391      0.6445     0.87996           0]
 [    0.54688     0.57623     0.89459     0.83282     0.87704           2]
 [    0.55777     0.32313     0.91398     0.57728     0.86747           2]
 [    0.29643     0.23651     0.36325     0.28729     0.86578           0]
 [    0.39674     0.83183     0.47572     0.89225     0.86428           0]
 [    0.37067      0.2345     0.43549     0.29423     0.86037           0]
 [     0.3869     0.74392     0.45128     0.78836     0.85802           0]
 [    0.55375     0.75004     0.62423     0.80525     0.83834           0]
 [     0.5506      0.5174     0.62426     0.57702     0.83029           0]
 [     0.2536     0.66259     0.31208     0.71512     0.81253           0]
 [    0.16143   

[[    0.48647     0.19321     0.67543      0.4214     0.94105           2]
 [     0.1314     0.73955     0.27722     0.89284     0.92575           2]
 [    0.27424     0.40781     0.45582     0.66508     0.92451           2]
 [    0.12992     0.20953     0.32852     0.34502     0.92103           2]
 [    0.21513      0.5948     0.27899      0.6469     0.89837           0]
 [    0.27301      0.3187     0.45958     0.42371     0.89582           2]
 [    0.56703     0.15639     0.62265     0.20324     0.89285           0]
 [     0.5054     0.42452     0.82459     0.67877     0.87969           2]
 [    0.65984     0.18587     0.81917     0.45891     0.87066           2]
 [    0.21514     0.66468      0.2732     0.71732     0.86764           0]
 [    0.56669     0.21472     0.62511     0.26293      0.8637           0]
 [    0.26889     0.79001     0.33265     0.84395      0.8614           0]
 [    0.13676     0.34811     0.28093     0.60632     0.85623           2]
 [    0.23209     0.36554

[[    0.68028     0.18351     0.88533      0.5815     0.94483           2]
 [    0.35174     0.18552     0.43727     0.45707     0.93181           2]
 [     0.5113     0.43949      0.6108     0.58517      0.9022           2]
 [    0.40695      0.5848     0.61041     0.98723     0.89476           2]
 [    0.43644     0.11514     0.53997     0.33651     0.88173           2]
 [    0.22065     0.71396     0.28321     0.81249     0.86947           2]
 [    0.39372     0.14324      0.4239     0.20017     0.86934           0]
 [    0.50875     0.53057     0.53717     0.58225     0.84744           0]
 [    0.35256     0.39129     0.38286     0.44923     0.84024           0]
 [    0.24476     0.59591     0.28106     0.66485     0.83968           0]
 [    0.32479     0.23968     0.35351     0.29359      0.8387           0]
 [    0.18591     0.80241     0.22304     0.86787     0.83649           0]
 [    0.86623     0.32686     0.89119     0.37109     0.83357           0]
 [    0.86287     0.52665

[[    0.29865     0.03401     0.48359     0.18571     0.91137           2]
 [    0.72352     0.30678     0.95078     0.56558     0.88803           2]
 [    0.72277     0.72961     0.78713      0.7881     0.88537           0]
 [    0.71924       0.517     0.78754      0.5701     0.87483           0]
 [    0.67734     0.72215     0.95778      0.8957     0.86185           2]
 [    0.61135     0.72826     0.67308     0.78104     0.84324           0]
 [    0.25626     0.63527     0.31087     0.67787     0.83194           0]
 [    0.67813     0.67754      0.7465     0.72841     0.82696           0]
 [    0.23004     0.89758     0.30038      0.9609     0.82061           0]
 [    0.23957     0.77581     0.30655     0.82662     0.80549           0]
 [    0.73573     0.88113      0.8282     0.90781     0.75702           1]
 [     0.3032     0.68069     0.47719     0.88959     0.75568           2]
 [    0.57539     0.88179     0.67242     0.90718      0.7443           1]
 [    0.33382     0.88031

[[    0.18131      0.5814     0.46856     0.69254     0.93208           2]
 [   0.038793     0.13958     0.23311     0.36674     0.90936           2]
 [    0.68347     0.10538     0.73888     0.14792     0.89722           0]
 [    0.49892      0.5837     0.59961     0.68838     0.89355           2]
 [    0.23672     0.10397      0.2918     0.15189     0.88972           0]
 [    0.17863     0.59125     0.23573     0.63321     0.88485           0]
 [    0.22076     0.13772      0.4704     0.36804     0.88393           2]
 [    0.68872     0.68595     0.93753     0.93011     0.87895           2]
 [     0.6796     0.49931     0.91488     0.68659     0.86864           2]
 [    0.61752     0.68245     0.67457     0.73263       0.867           0]
 [    0.23183     0.32129     0.28725     0.36253     0.86479           0]
 [    0.14219     0.53994      0.2005     0.58106     0.85975           0]
 [    0.22106     0.54607      0.2692     0.58507     0.85434           0]
 [    0.55205     0.54927

[[    0.72515     0.65083     0.94646     0.81434     0.90091           2]
 [    0.32215     0.14129      0.3823     0.21965     0.85305           0]
 [    0.74784     0.81105     0.80581     0.88405     0.81405           0]
 [    0.32156     0.22653     0.38758     0.30698     0.81179           0]
 [    0.83892     0.86985     0.91055     0.95148     0.77992           0]
 [    0.72028     0.21081     0.94676     0.61838     0.76672           2]]
1053.png
[[    0.48819     0.50062     0.84332     0.82264     0.92411           2]
 [      0.364     0.33818      0.4227      0.4317     0.88873           0]
 [    0.51486     0.49118     0.57535     0.59047     0.87993           0]
 [    0.38423     0.41814     0.44536     0.49711     0.87485           0]
 [    0.44148    0.067866     0.84269     0.51092     0.86839           2]
 [     0.2526     0.34811     0.31099     0.43225     0.85448           0]
 [    0.83317     0.37334     0.89253     0.47066     0.85153           0]
 [    0.82794  

[[    0.77233     0.10193     0.95899     0.41857     0.91569           2]
 [    0.68489     0.53999     0.96145     0.88629     0.88332           2]
 [    0.72445     0.36496     0.77125     0.43628     0.87023           0]
 [    0.68493     0.53523     0.73804     0.61024     0.86869           0]
 [    0.56211    0.037323     0.60932     0.10025     0.86351           0]
 [    0.54715       0.115     0.64525     0.27036      0.8498           2]
 [    0.67638     0.10806     0.77682     0.37078      0.8482           2]
 [    0.77561     0.37881      0.8209      0.4421     0.80087           0]
 [    0.56348     0.19114     0.60966     0.25983     0.76964           0]
 [    0.18613     0.22677     0.31693     0.36556     0.71393           2]
 [    0.40618     0.10008     0.48642     0.13183     0.71046           1]
 [    0.75341     0.86023      0.8644     0.89201     0.70743           1]]
1064.png
[[    0.60864     0.28164     0.89138     0.58471     0.94746           2]
 [    0.29942  

[[   0.030722    0.067401     0.23524     0.40789     0.94114           2]
 [    0.84969     0.33727     0.97885     0.86434      0.9326           2]
 [    0.22881     0.45039     0.31478     0.61398     0.92138           2]
 [    0.50201    0.080097     0.72048     0.45327     0.91947           2]
 [    0.50882     0.61553      0.6022     0.85027     0.91229           2]
 [    0.50916     0.46252     0.61812     0.62369     0.90134           2]
 [    0.70872     0.44128     0.85417     0.63735     0.89663           2]
 [    0.31049     0.43938      0.3906     0.62598     0.86437           2]
 [   0.032786     0.40174     0.10063     0.66795     0.85175           2]
 [     0.1869     0.40143     0.21512      0.4583     0.84711           0]
 [    0.10426     0.35449      0.1296     0.40659     0.84195           0]
 [    0.32231     0.61655     0.35105     0.67172     0.83488           0]
 [    0.58875     0.60788     0.61724     0.66317     0.83462           0]
 [    0.68713     0.55249

[[    0.87498     0.28728     0.93529     0.38116     0.85129           0]
 [    0.13664     0.58979     0.19366     0.65591     0.84967           0]
 [    0.27147     0.30412     0.33755     0.38132     0.81711           0]
 [     0.3385     0.57787     0.40268     0.66248     0.79136           0]
 [    0.33833     0.73628     0.41778     0.83255      0.7713           0]
 [   0.037772     0.51009     0.12894     0.71798     0.75094           2]]
1080.png
[[    0.29101     0.54349     0.37216     0.80254     0.92765           2]
 [    0.52072     0.14679     0.63216     0.43917     0.92618           2]
 [     0.8553     0.33617      0.8885     0.40506     0.91828           0]
 [    0.36252     0.12788     0.46968     0.63211     0.91725           2]
 [    0.85278     0.16574     0.96387     0.34158      0.8981           2]
 [    0.24211     0.78517      0.2743      0.8534     0.88448           0]
 [    0.51677     0.47235      0.6342     0.80977     0.88145           2]
 [    0.60195  

[[    0.21135     0.39541     0.56735     0.72328     0.94965           2]
 [    0.75865     0.41604     0.89544     0.64714     0.87687           2]
 [    0.70976     0.73608     0.76262     0.79113     0.87619           0]
 [   0.062297     0.10298     0.22348      0.4015     0.86127           2]
 [    0.69251     0.48872     0.75834     0.56766     0.84435           0]
 [    0.67004     0.87404     0.73469     0.96477     0.84325           0]
 [    0.55339     0.48038     0.62554     0.55813     0.84119           0]
 [    0.66982     0.77376     0.74018     0.86123     0.81883           0]
 [    0.15016     0.29917     0.22039     0.38859     0.81489           0]
 [    0.63108    0.057098     0.84116     0.36384     0.79414           2]
 [    0.67802    0.046022     0.81176    0.083181     0.71643           2]]
1087.png
[[    0.54224     0.40734     0.60446     0.45798     0.89582           0]
 [    0.53908       0.261     0.74719     0.49006     0.88547           2]
 [    0.45304  

[[    0.68478     0.55864     0.90261     0.81203     0.83407           2]]
1098.png
[[     0.6833     0.48847     0.97436     0.71816     0.92143           2]
 [    0.35156     0.81397      0.4924     0.98416     0.92123           2]
 [    0.20649    0.074571     0.26947     0.12949     0.91733           0]
 [    0.76842     0.31483     0.83021     0.36947     0.90257           0]
 [    0.76196     0.12055     0.97163     0.36654      0.9017           2]
 [    0.51833     0.40295     0.67773     0.59846     0.90005           2]
 [    0.29697     0.84577     0.35865     0.89843     0.89848           0]
 [    0.67385     0.35921     0.74176     0.42065     0.89694           0]
 [    0.20677      0.1287     0.26807     0.18701     0.89016           0]
 [    0.66826     0.44903     0.71709     0.48763     0.88454           0]
 [    0.53333     0.12281     0.75641     0.36642     0.88245           2]
 [    0.32257     0.52443     0.36934     0.56272     0.87405           0]
 [    0.27342  

[[    0.33404     0.41902     0.39655     0.51355     0.89721           0]
 [    0.24714     0.42412     0.30603     0.50872     0.88424           0]
 [    0.42634     0.50299      0.8304     0.88386     0.88285           2]
 [    0.25929     0.89737     0.32017     0.99732     0.86343           0]
 [    0.83658     0.35761     0.90106     0.44651       0.858           0]
 [    0.40708     0.52198     0.48289     0.61815     0.84141           0]
 [    0.23668     0.57719     0.30377     0.65799     0.83876           0]
 [     0.2404     0.74241     0.30133     0.83099     0.79577           0]
 [    0.75717     0.35781     0.82065     0.44276     0.78312           0]
 [    0.10566    0.034466     0.31748     0.44458     0.71407           2]]
1104.png
[[    0.10064    0.057263     0.24198     0.33058     0.93698           2]
 [    0.10096      0.5282     0.24212     0.79991     0.92753           2]
 [    0.24028     0.64152     0.37027     0.79965     0.92221           2]
 [    0.55767  

[[    0.52644     0.29445      0.9408     0.46997     0.95888           2]
 [    0.79069     0.51658     0.93861     0.72964     0.91268           2]
 [   0.071879     0.84344     0.19305     0.97046     0.91256           2]
 [   0.076831     0.74769     0.20336     0.84037       0.908           2]
 [    0.51159     0.62327     0.80637     0.83696     0.89207           2]
 [    0.73754     0.55731     0.79542     0.60366     0.88869           0]
 [     0.2026     0.74852     0.26899     0.80491     0.87146           0]
 [    0.18838     0.89595     0.24963     0.94319      0.8705           0]
 [    0.52856      0.4656     0.79312     0.62416     0.86496           2]
 [     0.1978     0.24478     0.25773     0.29247     0.86392           0]
 [    0.72551     0.42689     0.78119     0.47363     0.85403           0]
 [    0.72732     0.61735     0.79042     0.67487      0.8412           0]
 [    0.20494     0.84072     0.26811     0.89609     0.83995           0]
 [     0.1968     0.28624

[[     0.5079     0.44463     0.80463     0.78823      0.9401           2]
 [    0.47873     0.08112     0.80198     0.44303     0.92469           2]
 [   0.037049     0.46685     0.27953     0.87164     0.91115           2]
 [    0.38143     0.33096      0.4413     0.41045     0.89128           0]
 [    0.37524      0.2504     0.42616      0.3263     0.85331           0]
 [     0.2262     0.50553     0.28418     0.59499     0.85038           0]
 [   0.050647    0.054442     0.28421     0.48992     0.83812           2]
 [    0.39916     0.47366     0.44959     0.55368      0.8177           0]
 [    0.74375     0.32132     0.80108     0.41872     0.79896           0]
 [    0.27723     0.34306     0.33275     0.42577     0.78695           0]
 [    0.81025     0.31761     0.87416     0.41825     0.70691           0]]
1122.png
[[    0.46361     0.49838     0.58664     0.65626     0.94643           2]
 [    0.20188    0.048974     0.36432     0.22516     0.90861           2]
 [    0.30513  

[[    0.30846     0.75798     0.50216     0.97211     0.92846           2]
 [    0.48258     0.70445     0.93401     0.96829      0.8944           2]
 [    0.37878     0.70405     0.45358     0.77326     0.86931           0]
 [    0.49858     0.18497     0.57123     0.25185     0.83919           0]
 [   0.047176      0.5172     0.17328     0.66847     0.81124           2]
 [    0.23858      0.5932       0.312     0.66542     0.80649           0]
 [    0.16491     0.56811     0.23188     0.63542     0.79446           0]]
1129.png
[[    0.73392     0.60105     0.79367     0.67048     0.91186           0]
 [    0.24284      0.8852     0.29699     0.94065     0.90209           0]
 [    0.36514     0.20482     0.41876     0.26686     0.89976           0]
 [    0.30803     0.07297     0.49256     0.27768     0.88868           2]
 [    0.16721     0.60487      0.2246     0.66553     0.88383           0]
 [    0.63319     0.59995     0.69572     0.66999     0.88064           0]
 [    0.24399  

[[    0.11441      0.5802     0.48802     0.79286     0.93706           2]
 [    0.65706     0.50283     0.95139     0.79014     0.93439           2]
 [    0.10012    0.043196     0.63511     0.19504      0.9215           2]
 [    0.51147      0.1422     0.60793     0.19564     0.88573           0]
 [    0.38548     0.57894     0.49007     0.65375     0.88426           0]
 [    0.49546     0.79471     0.61215     0.86432     0.87353           0]
 [    0.47704     0.50315     0.58135     0.56511     0.87321           0]
 [    0.47879     0.40087     0.57413     0.45702     0.83138           0]
 [    0.80434     0.78245     0.92635     0.80794     0.81525           1]
 [    0.62955     0.79378     0.77405     0.95885     0.79118           2]
 [    0.76763     0.18609      0.8789     0.21211     0.76134           1]
 [    0.66499     0.55283     0.75563     0.61121     0.74072           0]]
638.png
[[    0.27272     0.75584     0.34371     0.80977     0.84421           0]
 [   0.099395   

[[     0.7133     0.33885     0.93061     0.49852     0.95701           2]
 [   0.059709     0.32746        0.39     0.49799     0.95058           2]
 [   0.070222     0.18098     0.24731     0.33818     0.94361           2]
 [    0.16186     0.61829     0.32667     0.76663     0.92699           2]
 [    0.51151     0.57716     0.85901     0.95245     0.92621           2]
 [    0.69541    0.079146     0.93443     0.26053     0.91513           2]
 [   0.074058     0.67848     0.16016      0.7614     0.91464           2]
 [    0.50904     0.80491     0.62224     0.94154      0.9046           2]
 [      0.542     0.53255     0.60864      0.5934     0.90249           0]
 [    0.61014     0.29209     0.66412     0.33861     0.89619           0]
 [   0.076164     0.58858     0.16081     0.68041     0.89464           2]
 [    0.64599     0.35739     0.69958     0.40604     0.89444           0]
 [    0.32158     0.58851     0.51699     0.76484     0.89406           2]
 [    0.61912     0.89586

[[    0.35659     0.11858     0.50251     0.30356     0.94847           2]
 [    0.35355     0.46463      0.4777     0.61895     0.92305           2]
 [    0.35089     0.60638     0.53547     0.88763     0.89651           2]
 [     0.5303     0.49319      0.6384     0.61593     0.86544           2]
 [    0.49875     0.38986     0.52999     0.43129     0.84753           0]
 [    0.49573     0.54139     0.53404     0.58717     0.84695           0]
 [    0.49703     0.61157     0.53471     0.66114      0.8414           0]
 [    0.46792     0.24409     0.50065     0.28759     0.84083           0]
 [    0.47136     0.49598     0.50402     0.53726     0.83051           0]
 [     0.5178     0.08087     0.55234     0.12861     0.81515           0]
 [     0.3555     0.30304     0.49945     0.46946      0.7556           2]
 [    0.50264    0.094073     0.63649     0.50432     0.75019           2]
 [    0.56001     0.11287       0.617     0.13308     0.70781           1]]
653.png
[[    0.59259   

[[     0.5497     0.68602      0.9934     0.84597     0.93921           2]
 [    0.54725     0.57941     0.77354     0.68722     0.92369           2]
 [    0.54293     0.73437     0.66628     0.78867     0.91836           0]
 [    0.43902      0.4841     0.55903     0.53701     0.91683           0]
 [    0.63697     0.87292     0.75714     0.92942     0.90651           0]
 [    0.74494     0.83872     0.98022     0.99398     0.90272           2]
 [    0.77072      0.5938     0.98287     0.68857     0.89721           2]
 [    0.79779     0.35364     0.91434     0.40896      0.8947           0]
 [    0.58647     0.34739     0.70671     0.40313     0.89276           0]
 [     0.7671     0.40696     0.98525     0.48025     0.88761           2]
 [    0.15428     0.84751     0.26944     0.90079     0.88034           0]
 [    0.44547     0.61297     0.56063     0.66037     0.87001           0]
 [    0.52961     0.43791     0.97735     0.59506     0.86506           2]
 [    0.77191     0.54362

[[     0.7364     0.62291     0.91252     0.76232      0.9326           2]
 [    0.41677     0.24877      0.5411     0.41256     0.92734           2]
 [    0.74069     0.62049     0.78996     0.66674     0.89436           0]
 [    0.84506     0.20936     0.89174     0.24918     0.89121           0]
 [    0.53892     0.24846     0.65104     0.47011     0.88965           2]
 [      0.583     0.21134      0.6303     0.25759     0.87305           0]
 [    0.48251     0.56917     0.53063     0.60884     0.85302           0]
 [    0.52652     0.41802     0.57649     0.45828      0.8515           0]
 [    0.56553     0.64407     0.60762     0.68445     0.83812           0]
 [    0.47486      0.7672     0.52919     0.81191     0.83749           0]
 [    0.83513      0.7233     0.87922     0.75963     0.83087           0]
 [    0.56467     0.53901     0.61345     0.58285     0.82694           0]
 [    0.48022     0.37154     0.53004     0.41838     0.81944           0]
 [    0.67639     0.46063

[[    0.23551    0.017547     0.33287     0.24297     0.89937           2]
 [    0.46363     0.47633     0.80778     0.67663     0.89075           2]
 [     0.5077     0.68105     0.80604     0.88239     0.88455           2]
 [    0.29289     0.67165      0.3553     0.76098     0.87754           0]
 [     0.0495      0.8884     0.11798     0.97235     0.87202           0]
 [    0.79471    0.052029     0.85888     0.13652     0.86984           0]
 [    0.51931     0.68135     0.57776     0.77416     0.86771           0]
 [    0.41322     0.70942     0.47038     0.78417     0.86579           0]
 [     0.7888     0.43515     0.99176     0.89054      0.8603           2]
 [    0.24197     0.23899     0.30463     0.32733     0.85507           0]
 [    0.13166     0.69414     0.19455     0.78468     0.85109           0]
 [    0.80276           0     0.92329     0.45994     0.84376           2]
 [   0.022355   0.0090129     0.24473     0.30477     0.83196           2]
 [    0.30736     0.54147

[[     0.2007     0.23063     0.67615     0.65705     0.88804           2]
 [    0.09246     0.19184     0.24459     0.43188     0.88194           2]
 [    0.28522    0.042866     0.68059     0.26315     0.84394           2]
 [    0.30767     0.19233     0.37672     0.25746     0.82667           0]
 [   0.088027     0.42518     0.25107     0.67014     0.82389           2]
 [    0.51196     0.67728     0.59243     0.75104     0.80573           0]
 [    0.10427     0.42319     0.17681     0.50407     0.80562           0]
 [    0.47752     0.66085     0.67894     0.95492     0.79974           2]
 [    0.11209     0.65912     0.19042     0.74014     0.77038           0]
 [    0.63945     0.29202     0.67782     0.44349     0.75013           2]
 [    0.64704    0.091702     0.67347     0.18809     0.71336           1]]
686.png
[[     0.4982      0.2491     0.73185     0.66298     0.91918           2]
 [   0.043303     0.52832     0.21111     0.85546     0.88067           2]
 [   0.046988   

698.png
[]
699.png
[[    0.41796     0.68018     0.53847     0.75466     0.88719           2]]
700.png
[]
701.png
[]
702.png
[[    0.52766     0.24326      0.6921      0.5031     0.89358           2]
 [    0.28226     0.43735     0.37401     0.50468     0.87369           2]
 [    0.76965     0.85767     0.83389      0.9667     0.85974           0]
 [    0.16379     0.32077     0.22146     0.42029     0.74631           2]
 [    0.72492     0.10715     0.88299     0.41781     0.72469           2]]
703.png
[[    0.71364     0.65356     0.77032       0.745     0.88163           0]
 [    0.38866      0.6305     0.44915     0.74284     0.86975           0]
 [    0.75658     0.31967     0.82232     0.41949     0.85863           0]
 [     0.2689     0.65885     0.32821     0.77476     0.79262           0]
 [    0.76099     0.20967     0.82338     0.30445     0.74679           0]
 [    0.52786    0.069432     0.73321     0.67872     0.70353           2]]
704.png
[[    0.53501     0.52747      0

[[    0.58249     0.50589     0.74869     0.60308      0.9227           2]
 [    0.46762     0.19112      0.8862      0.5032     0.90212           2]
 [    0.20462     0.14374     0.27703     0.19227     0.89937           0]
 [     0.1279     0.62139     0.45955     0.84393     0.89793           2]
 [    0.28355     0.54304     0.44489      0.6476     0.89568           2]
 [    0.59265     0.67943     0.67482     0.74613     0.88712           0]
 [      0.631     0.60059     0.69623     0.64829     0.87788           0]
 [    0.44338     0.57784     0.52154     0.63616     0.85152           0]
 [    0.49633     0.14138     0.57052       0.194     0.84608           0]
 [    0.44302     0.63661     0.59795     0.83582     0.84448           2]
 [    0.21449     0.38939     0.28034     0.44943     0.84197           0]
 [    0.36815     0.64557     0.44705      0.7141     0.83057           0]
 [    0.56209     0.83188     0.67859     0.98164     0.76714           2]
 [    0.57635     0.50884

[[    0.64863    0.090349     0.77443     0.29666     0.91464           2]
 [    0.77553      0.2011     0.83379     0.30056     0.90085           2]
 [    0.49842     0.82178     0.52963     0.86707     0.89731           0]
 [    0.66889     0.34414     0.74312     0.41125     0.88321           2]
 [     0.7734    0.096767     0.83127     0.20627     0.88238           2]
 [    0.19055      0.2137     0.26959     0.29466     0.87621           2]
 [    0.58389     0.74233     0.61349     0.78253     0.87137           0]
 [    0.86532     0.72153     0.88986     0.75656     0.86929           0]
 [    0.31862    0.043811     0.35638    0.099136     0.86885           0]
 [    0.56068     0.73684     0.68318     0.91182     0.86635           2]
 [    0.59804     0.64983     0.62677     0.69092     0.86133           0]
 [    0.74343     0.68899     0.77549     0.73202     0.85791           0]
 [    0.83258     0.13419     0.86439     0.17519      0.8565           0]
 [    0.53093      0.8041

[[    0.24364     0.55192     0.30004     0.65053     0.87762           0]
 [    0.18945     0.32014     0.23833     0.41227     0.87174           0]
 [    0.57408     0.37187     0.62463     0.45894     0.86725           0]
 [    0.30358      0.1821     0.34273     0.25595     0.86108           0]
 [    0.18891     0.52244     0.23826      0.6085     0.85992           0]
 [    0.24536     0.76647     0.29992     0.87328      0.8538           0]
 [     0.3437    0.073146     0.44531     0.35913     0.84976           2]
 [    0.62395     0.37536     0.67414     0.46332     0.84391           0]
 [    0.30176     0.27838     0.34383     0.35583     0.83193           0]]
721.png
[[    0.51238     0.35874     0.62993      0.5333     0.95943           2]
 [   0.011874      0.4185     0.15044     0.63519     0.93578           2]
 [    0.51489     0.11388     0.62809     0.37179     0.92798           2]
 [   0.025895    0.015077     0.26909     0.41531     0.91075           2]
 [    0.14199   

[[    0.69546     0.62691     0.79869      0.6837     0.84859           0]
 [    0.67153      0.4757     0.94604     0.69037     0.76747           2]
 [    0.55649      0.5642     0.66255     0.65534     0.70854           0]
 [    0.52888     0.67296     0.63197      0.7457     0.70754           0]]
733.png
[[     0.3154     0.88003     0.44426     0.96022      0.8548           0]]
734.png
[[    0.22975     0.23826     0.28975     0.30047       0.881           0]
 [    0.60376     0.54636     0.83855     0.82812     0.87536           2]
 [    0.47015    0.039535     0.62241     0.19123      0.8741           2]
 [    0.60663     0.56122     0.67255     0.63907     0.87325           0]
 [    0.52283     0.17955     0.57174     0.24028     0.87141           0]
 [    0.41327     0.67954     0.47625       0.763     0.86915           0]
 [    0.60872     0.19747     0.67368     0.26763     0.86753           0]
 [    0.14033     0.31725     0.19625     0.38487     0.86566           0]
 [   0.

[[    0.75748    0.054437     0.94766      0.4245     0.92929           2]
 [    0.56555     0.52799     0.75734      0.7538     0.90327           2]
 [    0.56526    0.051086     0.75918     0.44316      0.9019           2]
 [    0.75192     0.58899     0.79544     0.66826     0.87896           0]
 [     0.3571     0.52498     0.40187     0.60689     0.86342           0]
 [    0.36432     0.73991     0.41263     0.83545      0.8605           0]
 [     0.7715     0.36108     0.81359     0.44223     0.85237           0]
 [    0.76862       0.525     0.81299     0.61034     0.84617           0]
 [   0.071076     0.57147     0.16575     0.74952     0.84364           2]
 [    0.13166    0.063711     0.54994     0.42151     0.84286           2]
 [    0.24945     0.54663     0.29247     0.63028     0.84108           0]
 [    0.76188     0.43109      0.9487     0.75285     0.84017           2]
 [    0.12855     0.31272     0.16774     0.38609     0.83792           0]
 [    0.10813     0.49588

[[    0.57688     0.53568     0.64092     0.63426     0.89288           0]
 [    0.68167     0.36818     0.74354     0.45622     0.87116           0]
 [    0.67995     0.15628     0.73256     0.22069     0.85876           0]
 [     0.3207     0.57987     0.38354     0.66634     0.85411           0]
 [     0.2622     0.57593     0.32228      0.6639     0.85154           0]
 [    0.68634     0.53288     0.75519     0.63367     0.84325           0]
 [    0.30282     0.52587     0.66368     0.88233     0.80091           2]]
751.png
[[     0.6557     0.40932     0.94692     0.50976     0.82869           2]
 [    0.32213     0.57323     0.43625     0.63663     0.79516           0]
 [   0.047674      0.5524     0.42916     0.77204     0.78142           2]
 [    0.45549    0.095219     0.55451     0.14761     0.71735           0]]
752.png
[[    0.05292     0.60698     0.13833     0.73262      0.8765           2]
 [    0.13447     0.61757     0.17629     0.66997     0.83761           0]
 [   0.

[[    0.73037    0.071035     0.85783     0.30196     0.93975           2]
 [   0.058698    0.069701     0.26067       0.428     0.93658           2]
 [    0.53453     0.42356      0.6693       0.727     0.92325           2]
 [    0.66408     0.41957     0.79699     0.73588     0.92317           2]
 [    0.19515     0.47397     0.32128     0.75073     0.91625           2]
 [    0.25553    0.075077      0.4994     0.29617     0.91511           2]
 [    0.87274    0.074645     0.98203     0.39364     0.90742           2]
 [    0.63746     0.53038     0.67037     0.60801     0.88691           0]
 [    0.26173      0.4858     0.29174     0.55674     0.88574           0]
 [    0.73632     0.42122     0.76925     0.49711     0.88397           0]
 [    0.43619     0.28899     0.50599     0.39808     0.87052           2]
 [    0.77666     0.29095     0.80938      0.3656     0.86894           0]
 [    0.31662     0.49976     0.34863     0.57403     0.86365           0]
 [    0.84314     0.31582

[[    0.40094     0.65149     0.60373     0.83557     0.96386           2]
 [    0.59298     0.36859     0.88292     0.58341     0.95261           2]
 [     0.6933     0.56059     0.87256     0.84092     0.93163           2]
 [    0.43918     0.64818      0.4928     0.71265     0.89814           0]
 [    0.80469     0.29358      0.8623     0.35495     0.89527           0]
 [    0.55503     0.57127     0.60594     0.62975     0.88566           0]
 [     0.6953     0.57883     0.74791     0.63893      0.8813           0]
 [    0.64943     0.17338     0.69654     0.22885     0.88044           0]
 [    0.45923     0.30357     0.51191     0.36061     0.87885           0]
 [    0.30912     0.82561     0.36878     0.89237     0.86795           0]
 [    0.56186     0.38804      0.6088     0.44099     0.86434           0]
 [    0.62601     0.64669      0.6776     0.70986      0.8621           0]
 [    0.64624     0.53791     0.68136     0.57658     0.85775           0]
 [     0.1415     0.33484

[[   0.047853     0.33135     0.38463     0.60729     0.92832           2]
 [    0.65367     0.76435     0.72528     0.83847      0.7848           2]
 [    0.41389     0.43555     0.45834      0.4906     0.73577           0]]
772.png
[[    0.73064      0.7522      0.9831     0.90911     0.92393           2]
 [    0.73659     0.19559     0.97709     0.51359     0.90759           2]
 [    0.65677     0.56905     0.73983     0.62376     0.90502           0]
 [    0.61484     0.90128     0.71048     0.97579     0.90292           0]
 [    0.53318     0.14592     0.61556     0.20737     0.87347           0]
 [    0.83252     0.47331     0.90148     0.51931     0.87176           0]
 [    0.96031     0.26545     0.98504     0.29057     0.86913           1]
 [    0.27512     0.36791     0.36114     0.42716     0.85372           0]
 [    0.51282    0.059611     0.98913     0.21672     0.85151           2]
 [    0.63419     0.20309     0.70362     0.23034     0.82301           1]
 [     0.7372   

[]
788.png
[[    0.18418     0.51883     0.44628     0.64027     0.89937           2]]
789.png
[[    0.22438     0.50102     0.30402     0.55343     0.86685           0]
 [    0.50037     0.89076     0.60279     0.95873     0.86296           0]
 [   0.098958     0.35778     0.16839     0.40017     0.86056           0]
 [    0.28004     0.73609     0.36097     0.79651     0.80201           0]
 [   0.054546     0.39831     0.23633     0.49796     0.75854           2]
 [    0.16806     0.88105     0.33069     0.90299     0.72691           1]]
790.png
[[    0.23849     0.36677     0.26202     0.42501     0.80755           0]
 [    0.13943     0.36079     0.23317     0.58748     0.79223           2]
 [    0.44106     0.62133     0.49013     0.72456     0.74692           2]
 [    0.67305     0.43652     0.71108      0.5078     0.74635           2]
 [    0.76888     0.57263     0.78985     0.62031     0.74253           0]
 [    0.13992     0.35805     0.17027     0.42303     0.71852          

[[    0.42665     0.73919     0.47677     0.80127     0.86578           0]
 [    0.25356      0.2542     0.50398     0.60411     0.86124           2]
 [    0.68748     0.61342     0.91399     0.86599     0.85483           2]
 [    0.19363     0.68817     0.22289      0.7293     0.77089           0]
 [    0.55391      0.6688     0.60818     0.73329     0.76837           0]
 [    0.47907           0     0.69707     0.24495     0.75718           2]
 [    0.51716     0.53751     0.57749     0.61195     0.74698           0]
 [    0.60102     0.62614     0.66094      0.7211      0.7437           0]
 [    0.32066     0.81184     0.38761     0.89751     0.74077           0]
 [    0.44242     0.54111     0.48683     0.60972     0.71884           0]
 [    0.82592     0.86757     0.91767     0.94042      0.7086           2]]
799.png
[[    0.36149     0.59723      0.6533     0.84462     0.84095           2]]
800.png
[[    0.69042     0.75527     0.74721     0.82603     0.88604           0]
 [    0

[[    0.22992     0.22307     0.35189     0.48924     0.91223           2]
 [    0.68036     0.56641     0.81246     0.79812     0.89006           2]
 [    0.60193     0.80198     0.65312     0.88291     0.84693           0]
 [    0.74417     0.49667     0.78235     0.56778     0.83918           0]
 [    0.24317     0.22227     0.28733      0.3071     0.83899           0]
 [    0.18653     0.24713     0.23069     0.32306     0.82328           0]
 [    0.23106    0.079089     0.35373     0.22596     0.82064           2]
 [    0.71455     0.28734      0.7432     0.33951     0.79757           0]
 [     0.7158     0.49269     0.74297     0.54336     0.77385           0]
 [    0.71541     0.38931     0.74485     0.44141     0.77107           0]
 [    0.23339     0.42045     0.27727     0.48837     0.72507           0]]
810.png
[[    0.22992     0.22307     0.35189     0.48924     0.91223           2]
 [    0.68036     0.56641     0.81246     0.79812     0.89006           2]
 [    0.60193   

818.png
[[   0.073891     0.44245     0.13197     0.52409     0.80707           0]]
819.png
[[    0.35663    0.028761     0.63936     0.22961     0.95241           2]
 [    0.53923     0.15701     0.60022     0.22937     0.90807           0]
 [    0.53066     0.80447     0.58728     0.89585     0.90054           0]
 [    0.38269     0.65611      0.5197     0.81951     0.89023           2]
 [    0.52653     0.73694     0.58648     0.81497     0.86772           0]
 [    0.50985     0.67262     0.56928     0.74831      0.8435           0]
 [    0.38437     0.21345     0.62582     0.66307     0.83106           2]]
820.png
[[   0.049126     0.56529     0.18431     0.63046     0.89728           2]
 [    0.51881     0.54906      0.6428     0.63449     0.89311           2]
 [      0.289     0.51121     0.48431     0.74733     0.86063           2]
 [    0.63798     0.58787     0.69446     0.62964      0.8098           0]
 [    0.72373     0.57325     0.77055     0.61139     0.77431           0]

[[    0.28894     0.51859     0.42979     0.61405     0.88103           2]
 [    0.61806     0.52898     0.69254     0.57022     0.85413           0]
 [    0.18792     0.69031     0.25773     0.72696     0.81699           0]
 [    0.54624     0.01751     0.89397     0.21418      0.8155           2]
 [     0.5536     0.68942     0.63313     0.73305     0.79119           0]
 [   0.031928     0.63701     0.11738     0.67803     0.78344           0]
 [    0.72163     0.17999     0.78685     0.21369      0.7562           0]
 [    0.49171     0.82079     0.55605     0.85926     0.75024           0]
 [    0.43417     0.82391     0.49238     0.85777     0.74691           0]
 [    0.43589     0.56709     0.51001     0.60454     0.74329           0]
 [    0.71662     0.77437     0.80062     0.80678     0.73158           2]
 [    0.64249     0.77548     0.72009     0.80349     0.70966           2]]
829.png
[[   0.075632     0.30428     0.28861     0.50019     0.92613           2]
 [    0.84958   

[[    0.21901     0.60994     0.49111     0.68638     0.86441           2]
 [    0.23953    0.082381     0.74655     0.22155     0.76073           2]
 [    0.50374     0.71336     0.74613     0.85293     0.70678           2]
 [    0.23994     0.29517     0.38364     0.34018     0.70504           2]]
842.png
[[    0.31282     0.13209     0.47951     0.50739     0.93268           2]
 [    0.35467     0.64707     0.40972     0.74729     0.90798           0]
 [    0.69425     0.10553     0.75123     0.14823     0.88438           1]
 [    0.32113     0.50107     0.41173     0.65658     0.87558           2]
 [    0.26426      0.5628     0.31626     0.64822     0.87517           0]
 [    0.09177     0.65243     0.23825     0.90878     0.85641           2]
 [    0.21719     0.53241     0.26259       0.662     0.85425           2]
 [    0.33645     0.15037     0.36358     0.19289     0.84926           0]
 [    0.23896     0.70489     0.29838     0.80727     0.83371           0]
 [    0.16973   

[[    0.56024     0.54292     0.93912     0.71272     0.96239           2]
 [    0.51207      0.5314     0.56705     0.58033     0.88812           0]
 [   0.072146     0.46706     0.35403     0.70174     0.88194           2]
 [    0.77572     0.74518     0.82415     0.78309     0.87216           0]
 [    0.58144      0.7206     0.76387     0.80678     0.87076           2]
 [    0.57795     0.81916     0.62753     0.86855     0.86824           0]
 [    0.62484      0.8045     0.72192     0.92398     0.86803           2]
 [    0.62427     0.23657     0.66116     0.27293     0.85758           0]
 [    0.19067     0.72395     0.24737     0.77309     0.85554           0]
 [    0.30403     0.65264     0.35516     0.69427     0.82925           0]
 [    0.77649     0.71542     0.94405     0.79881     0.81635           2]
 [     0.2048     0.77248     0.24244     0.80753     0.81317           0]
 [    0.59177     0.13294     0.63071      0.1691     0.79087           0]
 [    0.50471     0.91651

[[    0.54535     0.75354     0.71397     0.84335     0.82528           0]
 [   0.082459     0.37771     0.26427     0.43781     0.79695           2]]
862.png
[[    0.67161     0.36091      0.8502      0.4286     0.71375           2]]
863.png
[[    0.51185     0.68473     0.62217     0.75366     0.88675           2]
 [   0.050114     0.51373     0.30691     0.81236     0.87018           2]
 [    0.20424     0.80241     0.28715     0.86794     0.80234           2]
 [    0.65135     0.80106     0.81603     0.87454     0.73901           2]
 [   0.061351     0.45147      0.1436     0.52032     0.72841           2]]
864.png
[[    0.60727     0.66423     0.65439     0.73176     0.86365           0]
 [    0.58401     0.34905     0.63724     0.41921     0.83728           0]
 [    0.59009     0.72924     0.65181     0.81657     0.83374           0]
 [    0.59383     0.82338     0.65046     0.90696     0.77699           0]
 [    0.21757     0.34922     0.27087     0.43256     0.76924           0

[[    0.31585    0.057712     0.42299      0.2861     0.93479           2]
 [    0.23277     0.71366     0.36525      0.8805     0.91553           2]
 [    0.53214     0.49727     0.63831     0.71991     0.91496           2]
 [     0.4395     0.71529     0.56039     0.88054     0.90333           2]
 [    0.23709     0.59975      0.3563     0.71359     0.89901           2]
 [    0.55648     0.71447     0.64001     0.88182     0.89527           2]
 [   0.091232     0.33205     0.15867     0.43943     0.89188           2]
 [    0.82345     0.27718     0.95562     0.44453     0.88537           2]
 [    0.36166     0.71316     0.44455     0.88218     0.88077           2]
 [    0.35719     0.59504      0.4456     0.71882     0.87969           2]
 [    0.76057     0.33183     0.82778     0.43727     0.87865           2]
 [    0.32868     0.64518      0.3575     0.68836     0.86826           0]
 [    0.31556    0.077426     0.34598     0.12231     0.86697           0]
 [    0.53101     0.52055

[[    0.36034     0.51571     0.47434     0.75601     0.93825           2]
 [    0.16659     0.63332     0.20898     0.70937     0.93232           2]
 [   0.044296     0.52215     0.16803       0.641     0.91785           2]
 [     0.7883     0.68463     0.93028       0.852      0.9101           2]
 [    0.70817     0.75791     0.80061     0.84545     0.89453           2]
 [    0.66449     0.75504      0.7113     0.84262     0.89442           2]
 [    0.17609     0.52253     0.35416     0.64095     0.88594           2]
 [    0.59634     0.76462     0.62603     0.80061     0.87887           0]
 [    0.37078     0.76038     0.41475     0.81647      0.8561           0]
 [    0.62922     0.72321     0.65415     0.75765     0.85209           0]
 [     0.6945    0.081758     0.72447     0.11843     0.84708           0]
 [    0.13996     0.71075     0.16954     0.74689     0.84452           0]
 [    0.62716     0.19199     0.69635     0.28246     0.84115           2]
 [    0.41228     0.75797

[[    0.61381     0.33096     0.87496     0.49411     0.92904           2]
 [    0.68644     0.49426     0.89024      0.7344     0.90046           2]
 [    0.32414     0.79101     0.38237     0.85046     0.89728           0]
 [    0.69151      0.4809       0.756     0.54318     0.89223           0]
 [    0.23774     0.53951      0.3031     0.60457     0.89163           0]
 [    0.51434     0.11091     0.68873     0.34119     0.88461           2]
 [    0.68458     0.10748     0.88108      0.3424     0.88393           2]
 [    0.61179     0.42166     0.65752      0.4671     0.88062           0]
 [    0.62055     0.29506     0.67818     0.34411     0.88028           0]
 [    0.61816     0.48063     0.68656      0.5457     0.87445           0]
 [    0.69159     0.29277      0.7456     0.34027     0.86958           0]
 [    0.30859     0.59341     0.36809     0.64411     0.86867           0]
 [    0.60995     0.36751     0.65618     0.41214     0.86505           0]
 [    0.38584     0.60379

[[    0.38661    0.067668     0.54923     0.34004     0.93733           2]
 [    0.19979    0.065831     0.32726     0.39624      0.9257           2]
 [    0.80823     0.27187     0.94739     0.50393     0.92461           2]
 [    0.31397       0.548     0.49882     0.85294     0.90602           2]
 [    0.81292     0.21316      0.8514     0.27806     0.89305           0]
 [    0.72587    0.066336     0.94774      0.2875     0.88724           2]
 [     0.7111     0.47679     0.94846     0.76632     0.88225           2]
 [    0.41833     0.27081     0.46015      0.3401     0.87899           0]
 [    0.80662     0.31963     0.84314     0.38053     0.87646           0]
 [    0.93898     0.15469     0.98101     0.22748     0.87297           0]
 [    0.27911     0.43226     0.32591     0.50945      0.8728           0]
 [    0.38588     0.17658     0.42781     0.24564     0.85697           0]
 [    0.23188     0.38433     0.27919     0.46993     0.85663           0]
 [    0.34522     0.43471

[[    0.34691     0.62076     0.42048     0.70526     0.81019           0]]
897.png
[[     0.3704     0.59072     0.66432     0.94681     0.79679           2]]
898.png
[[    0.37621     0.31466     0.44728     0.39567     0.87073           0]
 [     0.5932     0.47762     0.93723     0.80603     0.84497           2]
 [    0.28487     0.17096     0.36177     0.24451     0.77082           0]
 [    0.68745     0.40982      0.7575      0.4819     0.75168           0]
 [    0.10564     0.56662      0.1719     0.64655     0.71118           0]]
899.png
[[    0.24614     0.51975     0.43211     0.84359     0.90163           2]
 [    0.43747    0.020047     0.60642     0.39039     0.89497           2]
 [    0.55769     0.32639     0.60745     0.39147     0.89453           0]
 [    0.61968     0.32675     0.66673     0.38847     0.88827           0]
 [    0.37999     0.54872     0.43215     0.61508     0.88512           0]
 [    0.51032     0.56127     0.55886     0.62377     0.88498           0

[[    0.10633      0.5114     0.38174     0.67962     0.94794           2]
 [    0.10791     0.33782     0.37484     0.51576      0.9342           2]
 [    0.32874     0.55347     0.38738     0.59631      0.8943           0]
 [    0.33452     0.47059     0.38583     0.50847     0.89406           0]
 [    0.54044     0.34229     0.87101      0.5124       0.887           2]
 [     0.3943     0.63516     0.45287     0.67593     0.87667           0]
 [    0.55502     0.46349     0.60584     0.50497     0.87595           0]
 [     0.7968     0.46496      0.8529     0.50879     0.85691           0]
 [    0.41252     0.45559     0.45527     0.48928     0.85526           0]
 [     0.4878     0.45707     0.53242      0.4888     0.85485           0]
 [    0.39089     0.67553     0.45556     0.72199     0.85136           0]
 [    0.38236     0.34068     0.48225     0.46134     0.81317           2]
 [    0.85424     0.46273     0.91559     0.51313     0.79055           0]
 [     0.4862     0.34853

[[    0.39818     0.74372     0.46739     0.80662     0.88738           0]
 [    0.32596     0.58617     0.38171     0.70576     0.87661           2]
 [     0.5526     0.65853      0.5988     0.70375     0.85541           0]
 [    0.50534     0.69865     0.55136     0.73788     0.82264           0]
 [     0.4972     0.65745     0.54277     0.69809     0.81054           0]
 [   0.023814     0.73237     0.48354           1     0.79761           2]
 [    0.60025     0.66389     0.66296     0.72106     0.76699           0]
 [    0.50479      0.4822     0.86629     0.65904     0.70372           2]]
914.png
[[    0.21566       0.302     0.49297     0.54244     0.95421           2]
 [    0.51286     0.30678     0.65099     0.53637     0.90616           2]
 [     0.6455     0.30812      0.7683     0.54097     0.90586           2]
 [    0.67427     0.74542     0.71717     0.80153     0.88154           0]
 [     0.3645     0.30525     0.41214     0.36673     0.86846           0]
 [    0.39384   

[[    0.52004     0.68167     0.80713     0.86497      0.8227           2]
 [    0.18976     0.23602     0.35016     0.28825     0.77128           2]]
923.png
[[    0.44379     0.64001     0.64485     0.88097     0.90871           2]
 [    0.49319     0.57259     0.54766     0.63822     0.90492           0]
 [    0.79824     0.26523     0.85178     0.31976     0.89614           0]
 [    0.87096    0.072082     0.91881     0.12404     0.89031           0]
 [    0.37279      0.7043     0.41875      0.7512     0.88962           0]
 [    0.62611     0.86598     0.68977     0.92919     0.88797           0]
 [    0.47368     0.67724     0.52435     0.73088     0.87824           0]
 [    0.79693    0.029418     0.91889     0.23675     0.87721           2]
 [    0.22304     0.29627     0.30099     0.38533     0.87649           2]
 [    0.80962     0.32456     0.86117       0.376     0.87197           0]
 [    0.62117     0.77631     0.67283       0.829     0.87067           0]
 [    0.79937   

[[    0.54129     0.43251     0.67818     0.65538     0.93909           2]
 [    0.53675     0.64086     0.67691     0.89222     0.93099           2]
 [    0.54042     0.17536      0.7682     0.43614     0.91702           2]
 [    0.24533     0.79805     0.28965     0.89925     0.91031           2]
 [    0.86011     0.53921     0.95306      0.7081     0.87977           2]
 [    0.70994     0.76942     0.77137     0.88788     0.87158           2]
 [    0.76671     0.32715     0.79947     0.38875     0.86761           0]
 [    0.54045     0.46987     0.57788     0.53775     0.86315           0]
 [    0.50637     0.47166     0.54352     0.53857     0.86179           0]
 [    0.54237      0.3662     0.57625     0.42833     0.84872           0]
 [     0.6798     0.38307     0.71013     0.44052     0.84858           0]
 [    0.31291     0.68125     0.34177     0.73234     0.84723           0]
 [    0.86275     0.53565     0.89559     0.59322     0.84534           0]
 [    0.19335     0.79722

[[    0.27965     0.54473     0.45223     0.74971     0.93048           2]
 [    0.64205      0.3076     0.69054     0.36957     0.90967           0]
 [    0.63932      0.1732     0.74424      0.3738     0.90843           2]
 [    0.59582     0.27635     0.64082      0.3337     0.89311           0]
 [    0.40745      0.4408     0.45273     0.50118     0.87551           0]
 [    0.40833     0.55541     0.45377     0.61561     0.87533           0]
 [    0.51192     0.57093     0.56218     0.63251     0.86925           0]
 [    0.64545     0.40342     0.69095      0.4629     0.86841           0]
 [    0.31191     0.49576     0.35061     0.54856     0.86564           0]
 [    0.36014     0.44018     0.45343     0.55145     0.72742           2]
 [    0.45433     0.74019     0.50355     0.80511     0.72106           0]]
937.png
[[   0.030079     0.15346     0.30804     0.61383      0.9055           2]
 [    0.31665     0.59682     0.37691     0.67649      0.8802           0]
 [    0.43871   

[[    0.64914     0.27674     0.91915     0.45122     0.93745           2]
 [    0.17496     0.46048     0.44937     0.64864     0.92894           2]
 [     0.7937     0.45382     0.91841      0.6071     0.90955           2]
 [    0.58456     0.32289     0.65987     0.37737     0.89619           0]
 [    0.44733     0.77365      0.5221      0.8297      0.8873           0]
 [    0.43975     0.69849     0.49683     0.74015      0.8685           0]
 [    0.44076      0.5356     0.50649     0.58959     0.85692           0]
 [    0.12551     0.79684     0.19763     0.85082     0.85655           0]
 [    0.57167     0.51384     0.64626     0.56977     0.85076           0]
 [    0.85585     0.41681     0.90865     0.45519     0.82979           0]
 [    0.32527     0.69182      0.3817      0.7316      0.8248           0]
 [    0.58647     0.47221     0.65351     0.51062     0.79615           0]
 [    0.65105     0.45529     0.76232      0.5168     0.78107           2]
 [    0.17355     0.76639

[[     0.5324     0.19353     0.90836     0.36884     0.93528           2]
 [     0.5346     0.43161     0.71701     0.48274     0.88538           2]
 [    0.71893      0.4296     0.80312     0.45918     0.88028           0]
 [    0.53507     0.37327     0.69717     0.43359      0.8767           2]
 [    0.53405     0.53306     0.90803     0.66579      0.8743           2]
 [    0.54939      0.6635      0.7816     0.76125     0.87027           2]
 [    0.35789     0.15734     0.47238     0.19789     0.86598           0]
 [    0.43868     0.70608      0.5492      0.7469     0.85504           0]
 [    0.53357      0.5447     0.62337     0.57623     0.85189           0]
 [    0.69916     0.37346      0.9035      0.4322     0.84747           2]
 [    0.35451     0.66098      0.4701     0.70268     0.84247           0]
 [    0.45467     0.48801     0.54327     0.52061     0.81866           0]
 [    0.53012     0.33684     0.62168     0.36904     0.81843           0]
 [    0.45663     0.43857

[[    0.13388     0.82024      0.1887     0.90206     0.88965           0]
 [    0.13911     0.65895     0.19359     0.74007     0.87763           0]
 [   0.033504     0.43733     0.13537     0.57415     0.87536           2]
 [    0.73565     0.25145     0.78454     0.32903     0.85104           0]
 [    0.60404     0.38322     0.64551     0.45015     0.84182           0]
 [   0.081774     0.65213     0.23834     0.83547     0.82768           2]
 [    0.19901     0.50651     0.25092     0.58303     0.82279           0]
 [    0.13163     0.44747     0.18616     0.53355     0.81836           0]
 [     0.5995     0.32251     0.63244     0.37823      0.7999           0]
 [    0.71703     0.49568     0.92291     0.68225     0.79821           2]
 [    0.73637     0.25903       0.927     0.49341     0.77244           2]
 [    0.52098     0.37308     0.70582     0.67411     0.74142           2]
 [   0.031534     0.46414    0.043696     0.51844     0.71904           1]
 [    0.50348     0.38962

[[    0.25756     0.23968     0.47179     0.47382     0.92257           2]
 [    0.26099     0.79712     0.34984     0.94283     0.87962           2]
 [    0.34698     0.60827     0.38201     0.66057     0.85663           0]
 [    0.48366    0.079403     0.52474     0.13489     0.84938           0]
 [    0.40035     0.51628     0.43288       0.563     0.84915           0]
 [    0.63001     0.50933     0.66059      0.5528     0.84833           0]
 [    0.35911     0.56736      0.3981     0.61845     0.84108           0]
 [    0.62822     0.43407     0.66329     0.48159     0.83838           0]
 [    0.29332     0.56897      0.3293      0.6155     0.81247           0]
 [    0.52368     0.23941     0.73962     0.42403     0.77687           2]
 [    0.26987     0.56213     0.34641     0.67259     0.70128           2]]
975.png
[[    0.41707     0.33663     0.46853     0.42776     0.83175           0]
 [    0.35292      0.3605     0.40795     0.46336     0.82799           0]
 [    0.38401   

[[   0.049388     0.37816     0.21778     0.47546     0.92759           2]
 [   0.051395     0.10784     0.17204     0.17765     0.92716           2]
 [      0.455     0.35752     0.59942     0.47118     0.92163           2]
 [    0.82423    0.054284     0.94795      0.1381      0.9076           2]
 [    0.58153    0.062831     0.70222     0.13555     0.88655           2]
 [    0.73833     0.35414     0.95004     0.47701     0.88542           2]
 [    0.58572      0.1411     0.61944     0.17174     0.88193           0]
 [    0.82927     0.10648     0.86571     0.13868     0.87469           0]
 [    0.82918     0.14112      0.8645     0.17223     0.87361           0]
 [    0.74577     0.10179       0.813     0.26516     0.86968           2]
 [    0.31703     0.47112     0.35466     0.50839      0.8652           0]
 [    0.22199     0.35175     0.29095     0.47547     0.86486           2]
 [    0.22272     0.47241     0.26026      0.5081     0.86183           0]
 [    0.22246     0.62216

[[    0.45587     0.54122     0.67742     0.69788     0.94154           2]
 [    0.67387     0.54069     0.90439      0.6951      0.9345           2]
 [   0.083728     0.26911      0.3739     0.47218     0.92979           2]
 [    0.33533     0.80933     0.45501     0.87531     0.92696           2]
 [    0.73533     0.15609     0.91393     0.39935     0.92121           2]
 [    0.73118     0.69407     0.90981     0.87752      0.9064           2]
 [    0.15074     0.54144     0.44724     0.61669     0.90434           2]
 [    0.54561     0.32564     0.66561     0.39705     0.90228           2]
 [   0.098954     0.47347     0.17852     0.52339     0.88281           0]
 [    0.17396     0.87174     0.21272     0.89684     0.87973           0]
 [    0.66591      0.3308      0.7385     0.39745     0.87859           2]
 [     0.4562     0.80716     0.54211      0.8735     0.87595           2]
 [    0.46153     0.32708     0.54813     0.39852     0.86998           2]
 [    0.17352     0.47302

[[   0.031943     0.22905     0.25993     0.48601     0.91763           2]
 [    0.15398     0.52149     0.21018     0.57774     0.91506           0]
 [    0.25945     0.21494      0.4762     0.54871     0.89969           2]
 [     0.1898     0.43353     0.24731     0.49336     0.89758           0]
 [     0.8352     0.65515     0.89649     0.71408     0.89316           0]
 [    0.18513     0.17473     0.24099     0.23295     0.88955           0]
 [    0.71925     0.66127     0.77591     0.72215      0.8886           0]
 [     0.3429     0.64732      0.3939     0.70224     0.88843           0]
 [    0.25185      0.5035     0.31262     0.55821     0.88579           0]
 [    0.18394     0.23704     0.24471     0.30154     0.88399           0]
 [    0.83231     0.55803     0.89309     0.61847     0.88055           0]
 [    0.73905     0.86311     0.80303     0.92472     0.87847           0]
 [    0.20581      0.6627     0.25585     0.70961     0.87741           0]
 [    0.71382     0.77528

[[    0.66707      0.6299     0.92028     0.85866     0.91634           2]
 [    0.53943     0.16368     0.59022     0.22132     0.90559           0]
 [    0.78484     0.56886     0.84087     0.63316     0.90148           0]
 [    0.59979     0.67207     0.66024      0.7409     0.89755           0]
 [    0.54164     0.22967     0.59084     0.27622     0.88453           0]
 [    0.73088     0.63244     0.77041     0.68384     0.86834           0]
 [    0.53258     0.12926     0.77703     0.56635      0.8674           2]
 [    0.34148     0.51404     0.40877     0.59626     0.86528           0]
 [    0.42003     0.74462     0.49115     0.83841     0.86387           0]
 [    0.54234     0.36213     0.58835     0.41017     0.85933           0]
 [    0.86106      0.8141     0.90284     0.86219     0.85345           0]
 [    0.31037      0.6239     0.35993     0.67226     0.85245           0]
 [    0.39843     0.51738      0.6762     0.74272     0.83607           2]
 [    0.54111     0.29822